CREATE TABLE BRAND (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE PRICELIST (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE CURRENCY (
    ID INT PRIMARY KEY,
    CODE VARCHAR(10),
    NAME VARCHAR(255)
);

CREATE TABLE PRICE (
    ID INT PRIMARY KEY,
    BRANDID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICELISTID INT,
    PRODUCTID INT,
    PRIORITY INT,
    PRICE DECIMAL(10,2),
    CURRENCYID INT,
    FOREIGN KEY (BRANDID) REFERENCES BRAND(ID),
    FOREIGN KEY (PRICELISTID) REFERENCES PRICELIST(ID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (CURRENCYID) REFERENCES CURRENCY(ID)
);
